# Generated by Django 5.0.7 on 2024-07-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Pokemon',
        ),
    ]
