# Generated by Django 5.0.7 on 2024-07-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_models_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='visited',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='attack',
            field=models.CharField(default='Quick Attack', help_text="Enter this pokemon's main attack", max_length=200),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(help_text="Enter this pokemon's name", max_length=200, null=True, unique=True),
        ),
    ]
