# Generated by Django 5.0.7 on 2024-07-31 23:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_type_type_type_type_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='type',
            name='type_type_case_insensitive_unique',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='type_name_case_insensitive_unique', violation_error_message='Type already exists (case insensitive match)'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon.type'),
        ),
    ]
